package cn.com.data.engine.entity;

import java.util.Date;

public class DataSourceInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.driver_class
	 * @mbg.generated
	 */
	private String driverClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.db_user
	 * @mbg.generated
	 */
	private String dbUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.db_password
	 * @mbg.generated
	 */
	private String dbPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.db_type
	 * @mbg.generated
	 */
	private String dbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.db_name
	 * @mbg.generated
	 */
	private String dbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.create_date
	 * @mbg.generated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.update_by
	 * @mbg.generated
	 */
	private String updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.update_date
	 * @mbg.generated
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.remarks
	 * @mbg.generated
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_source.del_flag
	 * @mbg.generated
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.id
	 * @return  the value of data_source.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.id
	 * @param id  the value for data_source.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.description
	 * @return  the value of data_source.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.description
	 * @param description  the value for data_source.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.driver_class
	 * @return  the value of data_source.driver_class
	 * @mbg.generated
	 */
	public String getDriverClass() {
		return driverClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.driver_class
	 * @param driverClass  the value for data_source.driver_class
	 * @mbg.generated
	 */
	public void setDriverClass(String driverClass) {
		this.driverClass = driverClass == null ? null : driverClass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.url
	 * @return  the value of data_source.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.url
	 * @param url  the value for data_source.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.db_user
	 * @return  the value of data_source.db_user
	 * @mbg.generated
	 */
	public String getDbUser() {
		return dbUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.db_user
	 * @param dbUser  the value for data_source.db_user
	 * @mbg.generated
	 */
	public void setDbUser(String dbUser) {
		this.dbUser = dbUser == null ? null : dbUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.db_password
	 * @return  the value of data_source.db_password
	 * @mbg.generated
	 */
	public String getDbPassword() {
		return dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.db_password
	 * @param dbPassword  the value for data_source.db_password
	 * @mbg.generated
	 */
	public void setDbPassword(String dbPassword) {
		this.dbPassword = dbPassword == null ? null : dbPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.db_type
	 * @return  the value of data_source.db_type
	 * @mbg.generated
	 */
	public String getDbType() {
		return dbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.db_type
	 * @param dbType  the value for data_source.db_type
	 * @mbg.generated
	 */
	public void setDbType(String dbType) {
		this.dbType = dbType == null ? null : dbType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.db_name
	 * @return  the value of data_source.db_name
	 * @mbg.generated
	 */
	public String getDbName() {
		return dbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.db_name
	 * @param dbName  the value for data_source.db_name
	 * @mbg.generated
	 */
	public void setDbName(String dbName) {
		this.dbName = dbName == null ? null : dbName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.create_by
	 * @return  the value of data_source.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.create_by
	 * @param createBy  the value for data_source.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.create_date
	 * @return  the value of data_source.create_date
	 * @mbg.generated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.create_date
	 * @param createDate  the value for data_source.create_date
	 * @mbg.generated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.update_by
	 * @return  the value of data_source.update_by
	 * @mbg.generated
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.update_by
	 * @param updateBy  the value for data_source.update_by
	 * @mbg.generated
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.update_date
	 * @return  the value of data_source.update_date
	 * @mbg.generated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.update_date
	 * @param updateDate  the value for data_source.update_date
	 * @mbg.generated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.remarks
	 * @return  the value of data_source.remarks
	 * @mbg.generated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.remarks
	 * @param remarks  the value for data_source.remarks
	 * @mbg.generated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_source.del_flag
	 * @return  the value of data_source.del_flag
	 * @mbg.generated
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_source.del_flag
	 * @param delFlag  the value for data_source.del_flag
	 * @mbg.generated
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag == null ? null : delFlag.trim();
	}
}