package cn.com.data.engine.entity;

public class SearchExecute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_execute.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_execute.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_execute.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_execute.defineid
	 * @mbg.generated
	 */
	private Integer defineid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_execute.dsid
	 * @mbg.generated
	 */
	private Integer dsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_execute.id
	 * @return  the value of search_execute.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_execute.id
	 * @param id  the value for search_execute.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_execute.name
	 * @return  the value of search_execute.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_execute.name
	 * @param name  the value for search_execute.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_execute.url
	 * @return  the value of search_execute.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_execute.url
	 * @param url  the value for search_execute.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_execute.defineid
	 * @return  the value of search_execute.defineid
	 * @mbg.generated
	 */
	public Integer getDefineid() {
		return defineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_execute.defineid
	 * @param defineid  the value for search_execute.defineid
	 * @mbg.generated
	 */
	public void setDefineid(Integer defineid) {
		this.defineid = defineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_execute.dsid
	 * @return  the value of search_execute.dsid
	 * @mbg.generated
	 */
	public Integer getDsid() {
		return dsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_execute.dsid
	 * @param dsid  the value for search_execute.dsid
	 * @mbg.generated
	 */
	public void setDsid(Integer dsid) {
		this.dsid = dsid;
	}
}