package cn.com.data.engine.entity;

public class SearchDefine {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_define.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_define.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_define.params
	 * @mbg.generated
	 */
	private String params;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_define.paramtype
	 * @mbg.generated
	 */
	private String paramtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column search_define.dsid
	 * @mbg.generated
	 */
	private Integer dsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_define.id
	 * @return  the value of search_define.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_define.id
	 * @param id  the value for search_define.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_define.name
	 * @return  the value of search_define.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_define.name
	 * @param name  the value for search_define.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_define.params
	 * @return  the value of search_define.params
	 * @mbg.generated
	 */
	public String getParams() {
		return params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_define.params
	 * @param params  the value for search_define.params
	 * @mbg.generated
	 */
	public void setParams(String params) {
		this.params = params == null ? null : params.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_define.paramtype
	 * @return  the value of search_define.paramtype
	 * @mbg.generated
	 */
	public String getParamtype() {
		return paramtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_define.paramtype
	 * @param paramtype  the value for search_define.paramtype
	 * @mbg.generated
	 */
	public void setParamtype(String paramtype) {
		this.paramtype = paramtype == null ? null : paramtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column search_define.dsid
	 * @return  the value of search_define.dsid
	 * @mbg.generated
	 */
	public Integer getDsid() {
		return dsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column search_define.dsid
	 * @param dsid  the value for search_define.dsid
	 * @mbg.generated
	 */
	public void setDsid(Integer dsid) {
		this.dsid = dsid;
	}
}