package cn.com.data.engine.dao;

import java.util.List;
import java.util.Map;

import cn.com.data.engine.entity.DataSourceInfo;

public interface DataSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    int insert(DataSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    int insertSelective(DataSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    DataSourceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataSourceInfo record);
    
    List<Map> fetchDsList();
}