package cn.com.data.engine.dao;

import java.util.List;
import java.util.Map;

import cn.com.data.engine.entity.SearchExecute;

public interface SearchExecuteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	int insert(SearchExecute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	int insertSelective(SearchExecute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	SearchExecute selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SearchExecute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table search_execute
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SearchExecute record);
	
	List<Map> fetchExecuteList();
	
	Map fetchExecuteByUrl(String path);
	
}